//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanVe
    {
        public int MaSC { get; set; }
        public int MaGhe { get; set; }
        public bool DaBan { get; set; }
    
        public virtual Ghe Ghe { get; set; }
        public virtual SuatChieu SuatChieu { get; set; }
    }
}
