//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaManagementEntities : DbContext
    {
        public CinemaManagementEntities()
            : base("name=CinemaManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANVE> BANVEs { get; set; }
        public virtual DbSet<CT_HDNHAP> CT_HDNHAP { get; set; }
        public virtual DbSet<CTHD_SP> CTHD_SP { get; set; }
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<HDNHAPHANG> HDNHAPHANGs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIM> PHIMs { get; set; }
        public virtual DbSet<PHONGCHIEU> PHONGCHIEUx { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<SUATCHIEU> SUATCHIEUx { get; set; }
        public virtual DbSet<SUCO> SUCOes { get; set; }
        public virtual DbSet<THELOAI> THELOAIs { get; set; }
        public virtual DbSet<VE> VEs { get; set; }
    }
}
