//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghe
    {
        public Ghe()
        {
            this.BanVes = new HashSet<BanVe>();
            this.Ves = new HashSet<Ve>();
        }
    
        public int MaGhe { get; set; }
        public int SoGhe { get; set; }
        public int SoPhong { get; set; }
    
        public virtual ICollection<BanVe> BanVes { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
