//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDNhapHang
    {
        public HDNhapHang()
        {
            this.CTHDNhaps = new HashSet<CTHDNhap>();
        }
    
        public int SoHDNhap { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public decimal ThanhTien { get; set; }
        public int MaNVNhap { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual ICollection<CTHDNhap> CTHDNhaps { get; set; }
    }
}
