//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongChieu
    {
        public PhongChieu()
        {
            this.Ghes = new HashSet<Ghe>();
            this.SuatChieux = new HashSet<SuatChieu>();
        }
    
        public int SoPhong { get; set; }
        public int SLGhe { get; set; }
    
        public virtual ICollection<Ghe> Ghes { get; set; }
        public virtual ICollection<SuatChieu> SuatChieux { get; set; }
    }
}
