//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.CTHDSanPhams = new HashSet<CTHDSanPham>();
            this.HDNhapHangs = new HashSet<HDNhapHang>();
        }
    
        public int MaSP { get; set; }
        public string LoaiSP { get; set; }
        public string TenSP { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaSP { get; set; }
        public byte[] HinhAnhSP { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<CTHDSanPham> CTHDSanPhams { get; set; }
        public virtual ICollection<HDNhapHang> HDNhapHangs { get; set; }
    }
}
