//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuCo
    {
        public int MaSuCo { get; set; }
        public int MaNVBao { get; set; }
        public string DiaDiem { get; set; }
        public string CTSuCo { get; set; }
        public bool TinhTrang { get; set; }
        public decimal PhiSuaChua { get; set; }
        public System.DateTime NgayBaoSC { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
