//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public int SoHD { get; set; }
        public int MaVe { get; set; }
        public int MaSC { get; set; }
        public int MaGhe { get; set; }
        public int SoGhe { get; set; }
        public decimal GiaVe { get; set; }
    
        public virtual Ghe Ghe { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual SuatChieu SuatChieu { get; set; }
    }
}
